<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Plant;

class PlantSeeder extends Seeder
{
    public function run(): void
    {
        $trees = [
            [
                'scientific_name' => 'Olea europaea',
                'common_name' => 'Olive',
                'description' => 'Evergreen tree producing olives for oil and food.',
                'water_requirements' => 'Low to moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'chalky',  // تربة طميية
                'co2_absorption' => 'High',
                'cancer_risk_impact' => 'Reduces risk (olive oil)',
                'growth_min_months' => 36,
                'growth_max_months' => 60,
                'required_area' => 6.0,
                'image' => 'images/olive.jpg',
            ],
            [
                'scientific_name' => 'Malus domestica',
                'common_name' => 'Apple',
                'description' => 'Deciduous tree cultivated for its sweet fruits.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'peaty',
                'co2_absorption' => 'High',
                'cancer_risk_impact' => 'Reduces risk (antioxidants)',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 5.0,
                'image' => 'images/apple.jpg',
            ],
            [
                'scientific_name' => 'Punica granatum',
                'common_name' => 'Pomegranate',
                'description' => 'Fruit-bearing deciduous shrub or tree.',
                'water_requirements' => 'Moderate to high',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'sandy',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Reduces risk (rich in antioxidants)',
                'growth_min_months' => 18,
                'growth_max_months' => 30,
                'required_area' => 4.0,
                'image' => 'images/pomegranate.jpg',
            ],
            [
                'scientific_name' => 'Ficus carica',
                'common_name' => 'Fig',
                'description' => 'Tree producing soft, sweet fruits.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'peaty',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Reduces risk (fiber & antioxidants)',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 5.0,
                'image' => 'images/fig.jpg',
            ],
            [
                'scientific_name' => 'Prunus armeniaca',
                'common_name' => 'Apricot',
                'description' => 'Tree bearing small, golden-orange fruits.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'clay',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 4.5,
                'image' => 'images/apricot.jpg',
            ],
            [
                'scientific_name' => 'Prunus avium',
                'common_name' => 'Cherry',
                'description' => 'Tree known for its sweet or sour fruits.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'loamy',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 4.0,
                'image' => 'images/cherry.jpg',
            ],
            [
                'scientific_name' => 'Prunus domestica',
                'common_name' => 'Plum',
                'description' => 'Tree that produces a variety of plum fruits.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'clay',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 4.0,
                'image' => 'images/plum.jpg',
            ],
            [
                'scientific_name' => 'Juglans regia',
                'common_name' => 'Walnut',
                'description' => 'Large tree grown for its edible nuts.',
                'water_requirements' => 'High',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'peaty',
                'co2_absorption' => 'High',
                'cancer_risk_impact' => 'Low (rich in omega-3)',
                'growth_min_months' => 36,
                'growth_max_months' => 60,
                'required_area' => 7.0,
                'image' => 'images/walnut.jpg',
            ],
            [
                'scientific_name' => 'Prunus dulcis',
                'common_name' => 'Almond',
                'description' => 'Tree producing edible seeds known as almonds.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'sandy',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 5.0,
                'image' => 'images/almond.jpg',
            ],
            [
                'scientific_name' => 'Citrus sinensis',
                'common_name' => 'Orange',
                'description' => 'Citrus tree with sweet orange fruits.',
                'water_requirements' => 'High',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'clay',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 6.0,
                'image' => 'images/orange.jpg',
            ],
            [
                'scientific_name' => 'Citrus limon',
                'common_name' => 'Lemon',
                'description' => 'Small evergreen tree producing yellow fruit.',
                'water_requirements' => 'High',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'loamy',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 4.5,
                'image' => 'images/lemon.jpg',
            ],
            [
                'scientific_name' => 'Vitis vinifera',
                'common_name' => 'Grapevine',
                'description' => 'Climbing plant cultivated for grapes.',
                'water_requirements' => 'Moderate',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'loamy',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'None',
                'growth_min_months' => 18,
                'growth_max_months' => 30,
                'required_area' => 2.0,
                'image' => 'images/grape.jpg',
            ],
            [
                'scientific_name' => 'Cedrus libani',
                'common_name' => 'Lebanese Cedar',
                'description' => 'Symbolic evergreen tree native to the region.',
                'water_requirements' => 'Low',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'rocky',  // خارج الأنواع المحددة (ممكن نغيرها إلى loamy أو chalky)
                'co2_absorption' => 'Very high',
                'cancer_risk_impact' => 'None',
                'growth_min_months' => 60,
                'growth_max_months' => 120,
                'required_area' => 10.0,
                'image' => 'images/cedar.jpg',
            ],
            [
                'scientific_name' => 'Citrus reticulata',
                'common_name' => 'Mandarin (Tangerine)',
                'description' => 'Small citrus tree with sweet fruits.',
                'water_requirements' => 'High',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'silty',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 5.0,
                'image' => 'images/mandarin.jpg',
            ],
            [
                'scientific_name' => 'Pyrus communis',
                'common_name' => 'Pear',
                'description' => 'Fruit tree grown for its soft, juicy fruits.',
                'water_requirements' => 'Moderate to high',
                'sun_requirements' => 'Full sun',
                'soil_type' => 'silty',
                'co2_absorption' => 'Medium',
                'cancer_risk_impact' => 'Low',
                'growth_min_months' => 24,
                'growth_max_months' => 36,
                'required_area' => 5.0,
                'image' => 'images/pear.jpg',
            ],
        ];

        foreach ($trees as $tree) {
            Plant::create($tree);
        }
    }
}
